export const PROVIDERS = {
  antigravity: {
    id: 'antigravity',
    name: 'Antigravity Cloud',
    shortName: 'Antigravity',
    tagline: 'Google DeepMind & Antigravity Cloud',
    defaultModel: 'gemini-3.8-flash',
    defaultReasoning: 'high',
    models: [
      {
        id: 'gemini-3.8-flash',
        name: 'Gemini 3.8 Flash',
        version: '3.8',
        description: 'Mais recente, alta velocidade, excelente capacidade de raciocínio e codificação',
        badge: 'Recomendado',
        badgeColor: 'cyan',
      },
      {
        id: 'gemini-3.7-flash',
        name: 'Gemini 3.7 Flash',
        version: '3.7',
        description: 'Raciocínio híbrido balanceado com resposta rápida em tempo real',
        badge: 'Popular',
        badgeColor: 'indigo',
      },
      {
        id: 'gemini-3.1-pro',
        name: 'Gemini 3.1 Pro',
        version: '3.1',
        description: 'Raciocínio profundo para tarefas analíticas e arquitetura de software complexa',
        badge: 'Pro',
        badgeColor: 'purple',
      },
      {
        id: 'gemini-3.6-flash',
        name: 'Gemini 3.6 Flash',
        version: '3.6',
        description: 'Versão anterior ultra-estável com baixa latência de resposta',
        badge: 'Estável',
        badgeColor: 'zinc',
      },
      {
        id: 'claude-opus-5-5-high',
        name: 'Claude Opus 5.5',
        version: 'Opus 5.5',
        description: 'Modelo de raciocínio de alta capacidade da Anthropic integrado à nuvem',
        badge: 'Claude',
        badgeColor: 'amber',
      },
      {
        id: 'claude-sonnet-5-5-high',
        name: 'Claude Sonnet 5.5',
        version: 'Sonnet 5.5',
        description: 'Equilíbrio consagrado para programação e refatorações elegantes',
        badge: 'Claude',
        badgeColor: 'amber',
      },
      {
        id: 'gpt-oss-120b-medium',
        name: 'GPT-OSS 120B',
        version: '120B',
        description: 'Pesos abertos otimizados para tarefas de desenvolvimento e terminal',
        badge: 'Open Source',
        badgeColor: 'emerald',
      },
    ],
    reasoningLevels: [
      { id: 'low', label: 'Low', hint: 'Rápido, respostas diretas' },
      { id: 'medium', label: 'Médio', hint: 'Equilíbrio ideal' },
      { id: 'high', label: 'High', hint: 'Raciocínio aprofundado' },
    ],
    supportsFastMode: false,
  },
  codex: {
    id: 'codex',
    name: 'Codex',
    shortName: 'Codex',
    tagline: 'OpenAI Codex Engine com Fast Tier & Reasoning',
    defaultModel: 'gpt-6-luna',
    defaultReasoning: 'medium',
    models: [
      {
        id: 'gpt-6-luna',
        name: 'GPT-6 Luna',
        version: '6 Luna',
        description: 'Nova geração ágil e de alta precisão para desenvolvimento iterativo',
        badge: 'Mais Recente',
        badgeColor: 'purple',
      },
      {
        id: 'gpt-6-sol',
        name: 'GPT-6 Sol',
        version: '6 Sol',
        description: 'Excelente equilíbrio de geração arquitetural, debugging e testes',
        badge: 'Balanceado',
        badgeColor: 'indigo',
      },
      {
        id: 'gpt-6-astra',
        name: 'GPT-6 Astra',
        version: '6 Astra',
        description: 'Modelo flagship topo de linha para problemas de lógica e refatorações complexas',
        badge: 'Flagship',
        badgeColor: 'pink',
      },
      {
        id: 'gpt-6.1-sol',
        name: 'GPT-6.1 Sol',
        version: '6.1 Sol',
        description: 'Versão preview da evolução do Sol para refatorações extensas',
        badge: 'Preview',
        badgeColor: 'emerald',
      },
      {
        id: 'gpt-5.6-luna',
        name: 'GPT-5.6 Luna',
        version: '5.6 Luna',
        description: 'Ultra-rápido e direto para comandos pontuais de código e bash',
        badge: 'Ágil',
        badgeColor: 'cyan',
      },
      {
        id: 'gpt-5.6-sol',
        name: 'GPT-5.6 Sol',
        version: '5.6 Sol',
        description: 'Versátil e maduro para manipulação de arquivos e comandos git',
        badge: 'Versátil',
        badgeColor: 'blue',
      },
      {
        id: 'gpt-5.6-terra',
        name: 'GPT-5.6 Terra',
        version: '5.6 Terra',
        description: 'Alta densidade de processamento e throughput veloz',
        badge: 'Velocidade',
        badgeColor: 'amber',
      },
      {
        id: 'gpt-5.5',
        name: 'GPT-5.5',
        version: '5.5',
        description: 'Geração base confiável para desenvolvimento assistido por voz',
        badge: 'Estável',
        badgeColor: 'zinc',
      },
    ],
    reasoningLevels: [
      { id: 'low', label: 'Low', hint: 'Rápido, menor latência' },
      { id: 'medium', label: 'Médio', hint: 'Equilíbrio recomendado' },
      { id: 'high', label: 'High', hint: 'Raciocínio máximo' },
    ],
    supportsFastMode: true,
  },
};
